/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package adh.guessinggame;

import javax.swing.JOptionPane;

/**
 *
 * @author Brian
 */
public class GuessingGameGui extends javax.swing.JFrame {

    private GuessingGameService gs;
    public final int MIN_GUESS = 1;
    public final int MAX_GUESS = 100;

    /**
     * Creates new form GuessingGameGui
     */
    public GuessingGameGui() {
        super("Guessing Game");
        initComponents();
        guessNumberLabel.setText("Guess the number I am thinking of between "
                + MIN_GUESS + " and " + MAX_GUESS + ".");
        gs = new GuessingGameService(MIN_GUESS, MAX_GUESS);
        gs.setCorrectNumber();
        playAgainButton.setVisible(false);
        quitButton.setVisible(false);
        this.setLocationRelativeTo(null);
        setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        guessingGamePanel = new javax.swing.JPanel();
        guessButton = new javax.swing.JButton();
        guessTextField = new javax.swing.JTextField();
        guessNumberLabel = new javax.swing.JLabel();
        yourGuessLabel = new javax.swing.JLabel();
        outputLabel = new javax.swing.JLabel();
        playAgainButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        guessButton.setText("Guess");
        guessButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        guessButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guessButtonActionPerformed(evt);
            }
        });

        guessNumberLabel.setText("Guess the number I am thinking of between X and Y.");

        yourGuessLabel.setText("Your Guess:");

        playAgainButton.setText("Play Again");
        playAgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAgainButtonActionPerformed(evt);
            }
        });

        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout guessingGamePanelLayout = new javax.swing.GroupLayout(guessingGamePanel);
        guessingGamePanel.setLayout(guessingGamePanelLayout);
        guessingGamePanelLayout.setHorizontalGroup(
            guessingGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guessingGamePanelLayout.createSequentialGroup()
                .addGroup(guessingGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(guessingGamePanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(guessButton))
                    .addGroup(guessingGamePanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(guessingGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(guessingGamePanelLayout.createSequentialGroup()
                                .addComponent(yourGuessLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(guessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(guessNumberLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(outputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(guessingGamePanelLayout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(playAgainButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quitButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        guessingGamePanelLayout.setVerticalGroup(
            guessingGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(guessingGamePanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(guessNumberLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(guessingGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(guessTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yourGuessLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(guessButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(outputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(guessingGamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(playAgainButton)
                    .addComponent(quitButton))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(guessingGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(guessingGamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guessButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guessButtonActionPerformed
        String s = guessTextField.getText();
        //verify that the text is an int
        try {
            int i = Integer.parseInt(s);
            Feedback result = gs.testGuess(i);
            switch (result) {
                case TOO_HIGH:
                    outputLabel.setText("Your guess is too high!");
                    break;
                case TOO_LOW:
                    outputLabel.setText("Your guess is too low!");
                    break;
                case CORRECT:
                    outputLabel.setText("Congratulations, you have guessed the correct"
                            + " number!!!");
                    guessButton.setVisible(false);
                    playAgainButton.setVisible(true);
                    quitButton.setVisible(true);
                    break;
            }

            //the following line was helpful for debugging
            System.out.println("Correct Num: " + gs.getCorrectNumber());

        } catch (Exception e) {
            //message box warning that the guess must be numerical.
            JOptionPane.showMessageDialog(this, "The guess must be numerical",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guessButtonActionPerformed

    private void playAgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAgainButtonActionPerformed
        gs.setCorrectNumber();
        guessTextField.setText("");
        outputLabel.setText("");
        guessButton.setVisible(true);
        playAgainButton.setVisible(false);
        quitButton.setVisible(false);
    }//GEN-LAST:event_playAgainButtonActionPerformed

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton guessButton;
    private javax.swing.JLabel guessNumberLabel;
    private javax.swing.JTextField guessTextField;
    private javax.swing.JPanel guessingGamePanel;
    private javax.swing.JLabel outputLabel;
    private javax.swing.JButton playAgainButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JLabel yourGuessLabel;
    // End of variables declaration//GEN-END:variables
}
